package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vitor Emmanoel
 */

import lanchonete.Carrinho;
import lanchonete.Sanduiche;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import lanchonete.Cliente;

public class CarrinhoGUI extends javax.swing.JFrame {
    Carrinho addSanduba = new Carrinho();;
    Carrinho carrinho;
    ArrayList<Sanduiche> sandubas;
    ArrayList <Sanduiche> listaSanduba = addSanduba.getSandubas();
    
    /**
     * Creates new form PedidoGUI
     */
    public CarrinhoGUI() {
        initComponents();
        
        this.carrinho = new Carrinho();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonAdicionarSanduba = new javax.swing.JButton();
        jButtonRemoverSanduba = new javax.swing.JButton();
        jButtonVerPedido = new javax.swing.JButton();
        jButtonFinalizarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("CARRINHO");

        jButtonAdicionarSanduba.setText("Adicionar Sanduiche");
        jButtonAdicionarSanduba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarSandubaActionPerformed(evt);
            }
        });

        jButtonRemoverSanduba.setText("Remover Sanduiche");
        jButtonRemoverSanduba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverSandubaActionPerformed(evt);
            }
        });

        jButtonVerPedido.setText("Ver Pedido");
        jButtonVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPedidoActionPerformed(evt);
            }
        });

        jButtonFinalizarPedido.setText("Finalizar Pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVerPedido)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdicionarSanduba)
                            .addComponent(jButtonRemoverSanduba)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonFinalizarPedido)))
                        .addGap(122, 122, 122))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(jButtonAdicionarSanduba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRemoverSanduba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFinalizarPedido)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarSandubaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarSandubaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Montagem addSanduba = new Montagem();
        addSanduba.setVisible(true);        
    }//GEN-LAST:event_jButtonAdicionarSandubaActionPerformed

    private void jButtonRemoverSandubaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverSandubaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        sandubas = carrinho.getSandubas();
        if (sandubas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não há sanduiches no carrinho!");
        }

        int opcaosanduiche = -1;
        while (opcaosanduiche < 0 || opcaosanduiche > sandubas.size()) {

            String mensagem = "Escolha o item que deseja remover: \n\n";
            for (int i = 0; i < sandubas.size(); i++) {
                mensagem += (i) + 1 + ". " + sandubas.get(i) + "\n";
            }
            mensagem += "\nOpção: ";
            try {

                opcaosanduiche = 0;
                opcaosanduiche = Integer.parseInt(JOptionPane.showInputDialog(null, mensagem));

                Sanduiche sanduicheRemovida = sandubas.remove(opcaosanduiche - 1);
                JOptionPane.showMessageDialog(null, "\nItem " + sanduicheRemovida.getSabor() + " (" + sanduicheRemovida.getTamanho() + ") removida do carrinho!");
                break;
            } catch (IndexOutOfBoundsException e) {

                JOptionPane.showMessageDialog(null, "Opção inválida!");
                JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage());
                break;

            }

        }
    }//GEN-LAST:event_jButtonRemoverSandubaActionPerformed

    private void jButtonVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPedidoActionPerformed
        // TODO add your handling code here:
        carrinho.setSandubas(this.listaSanduba);
        JOptionPane.showMessageDialog(null, carrinho.verCarrinho());
    }//GEN-LAST:event_jButtonVerPedidoActionPerformed
    
    private void jButtonFinalizarPedidoPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.dispose();
        Cliente cliente1 = null;
        if (carrinho.getSandubas().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "O carrinho está vazio!");
                } else {

                    sandubas = carrinho.getSandubas();
                    double valorTotal = carrinho.calcularTotal(sandubas);
                    String sanduichesTexto = "";

                    for (Sanduiche p : carrinho.getSandubas()) {
                        sanduichesTexto += "sanduiche de " + p.getSabor() + " - " + p.getTamanho() + " - R$" + p.getPreco() + "\n";
                }

                JOptionPane.showMessageDialog(null, 
                    ""
                    + "========== Nota Fiscal =========="
                    + "\nCliente: " + cliente1.getNome()
                    + "\nTelefone: " + cliente1.getTelefone()
                    + "\nBairro: " + cliente1.getBairro()
                    + "\n\nCarrinho de Compras: \n" + sanduichesTexto
                    + "\nValor total: R$ " + valorTotal
                    + "\nForma de Pagamento: " + cliente1.getPay()
                );
            }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrinhoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrinhoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrinhoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrinhoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarrinhoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarSanduba;
    private javax.swing.JButton jButtonFinalizarPedido;
    private javax.swing.JButton jButtonRemoverSanduba;
    private javax.swing.JButton jButtonVerPedido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
