/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author nicolas
 */
public class Combo extends javax.swing.JFrame {

    /**
     * Creates new form CardapioGUI
     */
    public Combo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel58 = new javax.swing.JLabel();
        try {
            Crieseucombo =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "GUI.Combo_jLabel1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        pao = new javax.swing.JLabel();
        frances = new javax.swing.JLabel();
        tresqueijos = new javax.swing.JLabel();
        integral = new javax.swing.JLabel();
        novegraos = new javax.swing.JLabel();
        italiano = new javax.swing.JLabel();
        carne = new javax.swing.JLabel();
        frango = new javax.swing.JLabel();
        molhos = new javax.swing.JLabel();
        proteinas = new javax.swing.JLabel();
        ponto = new javax.swing.JLabel();
        ponto2 = new javax.swing.JLabel();
        ponto1 = new javax.swing.JLabel();
        ponto4 = new javax.swing.JLabel();
        ponto3 = new javax.swing.JLabel();
        ponto6 = new javax.swing.JLabel();
        ponto5 = new javax.swing.JLabel();
        preço = new javax.swing.JLabel();
        preço1 = new javax.swing.JLabel();
        preço2 = new javax.swing.JLabel();
        preço4 = new javax.swing.JLabel();
        preço3 = new javax.swing.JLabel();
        preço6 = new javax.swing.JLabel();
        preço5 = new javax.swing.JLabel();
        Fechar01 = new javax.swing.JButton();
        salame = new javax.swing.JLabel();
        calabresa = new javax.swing.JLabel();
        almondegas = new javax.swing.JLabel();
        ponto7 = new javax.swing.JLabel();
        preço7 = new javax.swing.JLabel();
        saladas = new javax.swing.JLabel();
        acompanhamentos = new javax.swing.JLabel();
        ponto8 = new javax.swing.JLabel();
        preço8 = new javax.swing.JLabel();
        preço9 = new javax.swing.JLabel();
        ponto9 = new javax.swing.JLabel();
        tomate = new javax.swing.JLabel();
        pepino = new javax.swing.JLabel();
        alface = new javax.swing.JLabel();
        cebola = new javax.swing.JLabel();
        azeitona = new javax.swing.JLabel();
        ketchup = new javax.swing.JLabel();
        barbecue = new javax.swing.JLabel();
        maionese = new javax.swing.JLabel();
        rose = new javax.swing.JLabel();
        chipotle = new javax.swing.JLabel();
        ponto10 = new javax.swing.JLabel();
        ponto11 = new javax.swing.JLabel();
        ponto12 = new javax.swing.JLabel();
        ponto13 = new javax.swing.JLabel();
        ponto14 = new javax.swing.JLabel();
        preço10 = new javax.swing.JLabel();
        preço11 = new javax.swing.JLabel();
        preço12 = new javax.swing.JLabel();
        preço13 = new javax.swing.JLabel();
        preço14 = new javax.swing.JLabel();
        ponto16 = new javax.swing.JLabel();
        preço15 = new javax.swing.JLabel();
        preço16 = new javax.swing.JLabel();
        preço17 = new javax.swing.JLabel();
        preço18 = new javax.swing.JLabel();
        preço20 = new javax.swing.JLabel();
        ponto15 = new javax.swing.JLabel();
        ponto17 = new javax.swing.JLabel();
        ponto18 = new javax.swing.JLabel();
        ponto19 = new javax.swing.JLabel();
        batata = new javax.swing.JLabel();
        nuggets = new javax.swing.JLabel();
        ponto20 = new javax.swing.JLabel();
        ponto21 = new javax.swing.JLabel();
        preço21 = new javax.swing.JLabel();
        preço22 = new javax.swing.JLabel();
        ponto23 = new javax.swing.JLabel();
        preço23 = new javax.swing.JLabel();
        preço24 = new javax.swing.JLabel();
        ponto22 = new javax.swing.JLabel();
        coca = new javax.swing.JLabel();
        guarana = new javax.swing.JLabel();

        jLabel58.setText("R$ 1.00");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pao.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        pao.setForeground(new java.awt.Color(255, 0, 0));
        pao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pao.setText("1. PÃO");

        frances.setText("Francês");

        tresqueijos.setText("Três Queijos");

        integral.setText("Integral");

        novegraos.setText("Nove Grãos");

        italiano.setText("Italiano c/ Queijo");

        carne.setText("Carne");

        frango.setText("Frango");

        molhos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        molhos.setForeground(new java.awt.Color(255, 0, 0));
        molhos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        molhos.setText("MOLHOS");

        proteinas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        proteinas.setForeground(new java.awt.Color(255, 0, 0));
        proteinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proteinas.setText("2. PROTEINAS");

        ponto.setText("...............................................................");

        ponto2.setText("...............................................................");

        ponto1.setText(".......................................................");

        ponto4.setText("............................................");

        ponto3.setText("........................................................");

        ponto6.setText("................................................................");

        ponto5.setText("................................................................");

        preço.setText("R$ 1.00");

        preço1.setText("R$ 2.00");

        preço2.setText("R$ 1.50");

        preço4.setText("R$ 2.00");

        preço3.setText("R$ 2.00");

        preço6.setText("R$ 7.00");

        preço5.setText("R$ 5.00");

        Fechar01.setText("OK");
        Fechar01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFechar01ActionPerformed(evt);
            }
        });

        salame.setText("Salame");

        calabresa.setText("Calabresa");

        almondegas.setText("Almondegas");

        ponto7.setText("................................................................");

        preço7.setText("R$ 8.00");

        saladas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        saladas.setForeground(new java.awt.Color(255, 0, 0));
        saladas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saladas.setText("3. SALADAS");

        acompanhamentos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        acompanhamentos.setForeground(new java.awt.Color(255, 0, 0));
        acompanhamentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acompanhamentos.setText("ACOMPANHAMENTOS");

        ponto8.setText("............................................................");

        preço8.setText("R$ 7.00");

        preço9.setText("R$ 10.00");

        ponto9.setText(".......................................................");

        tomate.setText("Tomate");

        pepino.setText("Pepino");

        alface.setText("Alface");

        cebola.setText("Cebola Roxa");

        azeitona.setText("Azeitona");

        ketchup.setText("Ketchup");

        barbecue.setText("Barbecue");

        maionese.setText("Maionese");

        rose.setText("Rose");

        chipotle.setText("Chipotle");

        ponto10.setText(".................");

        ponto11.setText("..................");

        ponto12.setText("...................");

        ponto13.setText("........");

        ponto14.setText("...............");

        preço10.setText("R$ 1.00");

        preço11.setText("R$ 2.00");

        preço12.setText("R$ 2.50");

        preço13.setText("R$ 2.00");

        preço14.setText("R$ 1.00");

        ponto16.setText("................");

        preço15.setText("R$ 1.00");

        preço16.setText("R$ 2.00");

        preço17.setText("R$ 1.00");

        preço18.setText("R$ 2.00");

        preço20.setText("R$ 3.00");

        ponto15.setText(".................");

        ponto17.setText("...............");

        ponto18.setText("........................");

        ponto19.setText("..................");

        batata.setText("Batata Frita");

        nuggets.setText("Nuggets");

        ponto20.setText("............");

        ponto21.setText("................");

        preço21.setText("R$ 5.00");

        preço22.setText("R$ 8.00");

        ponto23.setText("..................");

        preço23.setText("R$ 6.00");

        preço24.setText("R$ 8.00");

        ponto22.setText(".............");

        coca.setText("Coca-Cola");

        guarana.setText("Guaraná");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acompanhamentos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saladas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(azeitona)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preço14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alface)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preço12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pepino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preço11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cebola)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preço13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tomate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preço10)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(molhos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chipotle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ponto19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rose)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ponto18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maionese)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ponto17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(barbecue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ponto16))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ketchup)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ponto15)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(preço17)
                                    .addComponent(preço18)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(preço20)
                                            .addComponent(preço16)
                                            .addComponent(preço15)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(almondegas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ponto9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calabresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ponto8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carne)
                                    .addComponent(frango))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ponto5)
                                    .addComponent(ponto6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(salame)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preço5)
                            .addComponent(preço6)
                            .addComponent(preço7)
                            .addComponent(preço8)
                            .addComponent(preço9)))
                    .addComponent(proteinas)
                    .addComponent(pao)
                    .addComponent(Crieseucombo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(ponto4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(novegraos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(integral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tresqueijos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(frances)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ponto))
                            .addComponent(italiano))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preço4)
                            .addComponent(preço3)
                            .addComponent(preço2)
                            .addComponent(preço)
                            .addComponent(preço1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Fechar01)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(guarana)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ponto21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(preço22))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(coca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ponto20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(preço21)))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nuggets)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ponto23))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(batata)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ponto22)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(preço24)
                                .addComponent(preço23)))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Crieseucombo)
                .addGap(18, 18, 18)
                .addComponent(pao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(frances)
                                .addComponent(ponto))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tresqueijos)
                                .addComponent(ponto1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(integral)
                                .addComponent(ponto2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(novegraos)
                                .addComponent(ponto3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(italiano))
                        .addComponent(ponto4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preço)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço4)))
                .addGap(18, 18, 18)
                .addComponent(proteinas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carne)
                            .addComponent(ponto5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frango)
                            .addComponent(ponto6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(preço6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salame)
                    .addComponent(ponto7)
                    .addComponent(preço7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calabresa)
                    .addComponent(ponto8)
                    .addComponent(preço8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(almondegas)
                    .addComponent(ponto9)
                    .addComponent(preço9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saladas)
                    .addComponent(molhos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tomate)
                                .addComponent(ponto10)
                                .addComponent(preço10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pepino)
                                .addComponent(ponto11)
                                .addComponent(preço11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(alface)
                                .addComponent(ponto12)
                                .addComponent(preço12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cebola)
                                .addComponent(ponto13)
                                .addComponent(preço13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(azeitona)
                                .addComponent(ponto14)
                                .addComponent(preço14)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ketchup)
                                .addComponent(ponto15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(barbecue)
                                .addComponent(ponto16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(maionese)
                                .addComponent(ponto17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rose)
                                .addComponent(ponto18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chipotle)
                                .addComponent(ponto19))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preço15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço20)))
                .addGap(18, 18, 18)
                .addComponent(acompanhamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(coca)
                                .addComponent(ponto20)
                                .addComponent(preço21))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(guarana)
                                .addComponent(ponto21)
                                .addComponent(preço22)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(batata)
                                .addComponent(ponto22))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nuggets)
                                .addComponent(ponto23))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preço23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preço24)))
                .addGap(18, 18, 18)
                .addComponent(Fechar01)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFechar01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFechar01ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jFechar01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Crieseucombo;
    private javax.swing.JButton Fechar01;
    private javax.swing.JLabel acompanhamentos;
    private javax.swing.JLabel alface;
    private javax.swing.JLabel almondegas;
    private javax.swing.JLabel azeitona;
    private javax.swing.JLabel barbecue;
    private javax.swing.JLabel batata;
    private javax.swing.JLabel calabresa;
    private javax.swing.JLabel carne;
    private javax.swing.JLabel cebola;
    private javax.swing.JLabel chipotle;
    private javax.swing.JLabel coca;
    private javax.swing.JLabel frances;
    private javax.swing.JLabel frango;
    private javax.swing.JLabel guarana;
    private javax.swing.JLabel integral;
    private javax.swing.JLabel italiano;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel ketchup;
    private javax.swing.JLabel maionese;
    private javax.swing.JLabel molhos;
    private javax.swing.JLabel novegraos;
    private javax.swing.JLabel nuggets;
    private javax.swing.JLabel pao;
    private javax.swing.JLabel pepino;
    private javax.swing.JLabel ponto;
    private javax.swing.JLabel ponto1;
    private javax.swing.JLabel ponto10;
    private javax.swing.JLabel ponto11;
    private javax.swing.JLabel ponto12;
    private javax.swing.JLabel ponto13;
    private javax.swing.JLabel ponto14;
    private javax.swing.JLabel ponto15;
    private javax.swing.JLabel ponto16;
    private javax.swing.JLabel ponto17;
    private javax.swing.JLabel ponto18;
    private javax.swing.JLabel ponto19;
    private javax.swing.JLabel ponto2;
    private javax.swing.JLabel ponto20;
    private javax.swing.JLabel ponto21;
    private javax.swing.JLabel ponto22;
    private javax.swing.JLabel ponto23;
    private javax.swing.JLabel ponto3;
    private javax.swing.JLabel ponto4;
    private javax.swing.JLabel ponto5;
    private javax.swing.JLabel ponto6;
    private javax.swing.JLabel ponto7;
    private javax.swing.JLabel ponto8;
    private javax.swing.JLabel ponto9;
    private javax.swing.JLabel preço;
    private javax.swing.JLabel preço1;
    private javax.swing.JLabel preço10;
    private javax.swing.JLabel preço11;
    private javax.swing.JLabel preço12;
    private javax.swing.JLabel preço13;
    private javax.swing.JLabel preço14;
    private javax.swing.JLabel preço15;
    private javax.swing.JLabel preço16;
    private javax.swing.JLabel preço17;
    private javax.swing.JLabel preço18;
    private javax.swing.JLabel preço2;
    private javax.swing.JLabel preço20;
    private javax.swing.JLabel preço21;
    private javax.swing.JLabel preço22;
    private javax.swing.JLabel preço23;
    private javax.swing.JLabel preço24;
    private javax.swing.JLabel preço3;
    private javax.swing.JLabel preço4;
    private javax.swing.JLabel preço5;
    private javax.swing.JLabel preço6;
    private javax.swing.JLabel preço7;
    private javax.swing.JLabel preço8;
    private javax.swing.JLabel preço9;
    private javax.swing.JLabel proteinas;
    private javax.swing.JLabel rose;
    private javax.swing.JLabel saladas;
    private javax.swing.JLabel salame;
    private javax.swing.JLabel tomate;
    private javax.swing.JLabel tresqueijos;
    // End of variables declaration//GEN-END:variables
}
